apiVersion: v1
kind: Service
metadata:
  name: notification
  labels:
    app: notification
spec:
  selector:
    app: notification # has to match .metadata.labels && template.metadata.labels of deployment || stafulset
  ports:
    - port: 80
      targetPort: 8050 # has to match containerPort of deployment || stafulset
  type: ClusterIP #IP address
