apiVersion: v1
kind: Service
metadata:
  name: orders
  labels:
    app: orders
spec:
  selector:
    app: orders # has to match .metadata.labels && template.metadata.labels of deployment || stafulset
  ports:
    - port: 80
      targetPort: 8030 # has to match containerPort of deployment || stafulset
  type: ClusterIP #IP address
