apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app: payment
spec:
  selector:
    app: payment # has to match .metadata.labels.app && template.metadata.labels.app of deployment || stafulset
  ports:
    - port: 80
      name: http
      targetPort: 8040 # has to match containerPort of deployment || stafulset
  type: ClusterIP #IP address
