version: "3.8"
services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring
networks:
  mysql:
    driver: bridge
  spring:
    driver: bridge
#volumes:
#  data:
