server:
  port: 8020
spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://localhost:3306/product
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show_sql: true