apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
      annotations:
        kubernetes.io/change-cause: "ntloc/notification:14.09.2022.17.51.54"
    spec:
      containers:
        - name: notification
          image: ntloc/notification:14.09.2022.17.51.54
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8050
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: eks
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: db_password
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: keysecret
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: keysecret
                  key: aws_secret_access_key
      restartPolicy: Always