apiVersion: v1
kind: Service
metadata:
  name: customer
  labels:
    app: customer
spec:
  selector:
    app: customer # has to match .metadata.labels && template.metadata.labels of deployment || stafulset
  ports:
    - port: 80
      targetPort: 8010 # has to match containerPort of deployment || stafulset
  type: LoadBalancer #IP address
