server:
  port: 8030
spring:
  application:
    name: orders
  datasource:
    url: jdbc:mysql://localhost:3306/orders
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show_sql: true