#Server
server:
  port: 8050
  servlet:
    context-path: /notification
  error:
    include-message: always
#Management
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#Spring
spring:
  application:
    name: notification
  datasource:
    url: jdbc:mysql://localhost:3306/notification
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show_sql: true
  zipkin:
    baseUrl: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
#Eureka-Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
#RabbitMQ
rabbitmq:
  exchange:
    internal: internal.exchange
  routing-key:
    internal-notification: internal.notification.routing-key
  queue:
    notification: notification.queue

