#Server
server:
  port: 8050
  error:
    include-message: always
#Spring
spring:
  application:
    name: notification
  datasource:
    url: jdbc:mysql://localhost:3306/notification
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show_sql: true
#  zipkin:
#    baseUrl: http://localhost:9411
#Eureka-Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
