apiVersion: v1
kind: Service
metadata:
  name: product
  labels:
    app: product
spec:
  selector:
    app: product # has to match .metadata.labels.app && template.metadata.labels.app of deployment || stafulset
  ports:
    - port: 80
      targetPort: 8020 # has to match containerPort of deployment || stafulset
  type: ClusterIP #IP address
