server:
  port: 8040
spring:
  application:
    name: payment
  datasource:
    url: jdbc:mysql://localhost:3306/payment
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show_sql: true