#Server
server:
  port: 8040
  servlet:
    context-path: /payment
  error:
    include-message: always
#Management
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#Spring
spring:
  application:
    name: payment
  datasource:
    url: jdbc:mysql://localhost:3306/payment
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show_sql: true
  zipkin:
    baseUrl: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
#Eureka-Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true