# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CD Deploy to AWS EKS

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Generate image tag
      id: image-tag
      run: echo "::set-output name=IMAGE_TAG::$(date '+%d.%m.%Y.%H.%M.%S')"

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Maven Clean Package & Push Image To DockerHub
      run: mvn clean package
        -Dimage.custom.tag=${{ steps.image-tag.outputs.IMAGE_TAG }}
        -P jib-build-push-image-to-dockerhub

    - name: Update and commit k8s resources
      run: |
        IMAGE_TAG=${{ steps.image-tag.outputs.IMAGE_TAG }}
        echo -e "Current kubernetes/aws-eks/services/customer/deployment.yml\n$(cat kubernetes/aws-eks/services/customer/deployment.yml)"
        sed -i -E 's_(ntloc/customer:)([^"]*)_\1'${IMAGE_TAG}'_' kubernetes/aws-eks/services/customer/deployment.yml
        echo -e "Current kubernetes/aws-eks/services/customer/deployment.yml\n$(cat kubernetes/aws-eks/services/customer/deployment.yml)"

        echo -e "Current kubernetes/aws-eks/services/product/deployment.yml\n$(cat kubernetes/aws-eks/services/product/deployment.yml)"
        sed -i -E 's_(ntloc/product:)([^"]*)_\1'${IMAGE_TAG}'_' kubernetes/aws-eks/services/product/deployment.yml
        echo -e "Current kubernetes/aws-eks/services/product/deployment.yml\n$(cat kubernetes/aws-eks/services/product/deployment.yml)"

        echo -e "Current kubernetes/aws-eks/services/orders/deployment.yml\n$(cat kubernetes/aws-eks/services/orders/deployment.yml)"
        sed -i -E 's_(ntloc/orders:)([^"]*)_\1'${IMAGE_TAG}'_' kubernetes/aws-eks/services/orders/deployment.yml
        echo -e "Current kubernetes/aws-eks/services/orders/deployment.yml\n$(cat kubernetes/aws-eks/services/orders/deployment.yml)"

        echo -e "Current kubernetes/aws-eks/services/payment/deployment.yml\n$(cat kubernetes/aws-eks/services/payment/deployment.yml)"
        sed -i -E 's_(ntloc/payment:)([^"]*)_\1'${IMAGE_TAG}'_' kubernetes/aws-eks/services/payment/deployment.yml
        echo -e "Current kubernetes/aws-eks/services/payment/deployment.yml\n$(cat kubernetes/aws-eks/services/payment/deployment.yml)"

        echo -e "Current kubernetes/aws-eks/services/notification/deployment.yml\n$(cat kubernetes/aws-eks/services/notification/deployment.yml)"
        sed -i -E 's_(ntloc/notification:)([^"]*)_\1'${IMAGE_TAG}'_' kubernetes/aws-eks/services/notification/deployment.yml
        echo -e "Current kubernetes/aws-eks/services/notification/deployment.yml\n$(cat kubernetes/aws-eks/services/notification/deployment.yml)"

        git config user.name github-actions
        git config user.email github-actions@github.com
        git add kubernetes/aws-eks/services/customer/deployment.yml
        git add kubernetes/aws-eks/services/product/deployment.yml
        git add kubernetes/aws-eks/services/orders/deployment.yml
        git add kubernetes/aws-eks/services/payment/deployment.yml
        git add kubernetes/aws-eks/services/notification/deployment.yml
        git commit -m "new app version: ${IMAGE_TAG}"
        git push

    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.21.5'
      id: install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Update kube config
      run: aws eks update-kubeconfig --name simple-market --region ap-southeast-1

    - name: Deploy to AWS EKS
      run: |
        kubectl apply -f kubernetes/aws-eks/services/customer/deployment.yml
        kubectl apply -f kubernetes/aws-eks/services/product/deployment.yml
        kubectl apply -f kubernetes/aws-eks/services/orders/deployment.yml
        kubectl apply -f kubernetes/aws-eks/services/payment/deployment.yml
        kubectl apply -f kubernetes/aws-eks/services/notification/deployment.yml
